---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-temp
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 60000
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
