---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress
  namespace: cert-manager
spec:
  acme:
    email: oso12_90@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    #disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: lets-encrypt-private-key
      key: private-key
    solvers:
    - http01:
        ingress:
          class: gce
      selector:
        dnsZones:
        - 'snwbr.net'
    # - dns01:
    #     cloudDNS:
    #       # The ID of the GCP project
    #       project: test-snwbr
    #       # This is the secret used to access the service account
    #       serviceAccountSecretRef:
    #         name: clouddns-dns01-solver-svc-acct
    #         key: key.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-staging
  namespace: cert-manager
spec:
  acme:
    email: oso12_90@hotmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: lets-encrypt-private-key-staging
      key: private-key
    solvers:
    - http01:
        ingress:
          class: gce
      selector:
        dnsZones:
        - 'snwbr.net'
    # - dns01:
    #     cloudDNS:
    #       # The ID of the GCP project
    #       project: test-snwbr
    #       # This is the secret used to access the service account
    #       serviceAccountSecretRef:
    #         name: clouddns-dns01-solver-svc-acct
    #         key: key.json