---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    users: AgB72SwnsS2e2LBe5E1G3pZTz1yHHgLsSFFc7zHBVINwtkLEw8pWzXygz5oUMt2y1ZVC3NKqyi/CENCd1uZOMnWy3RWaKPqW8nM2TUjaoJj9oWos5XZtRzqpgzhnvVnsstMqhapmwkO8Zz39dCcdhzCcA+tFRwlJF+dZIdLISgEklc85qPja90+7HdMeb9U+3yR51Hf5YCs1Pz+6FcHv0rl2t7mHn7QBc3oY5rOSwZ1orA4TD/Q0JE6EEj/lrlRWEZ+tZDHGTpd1NB+SeT6xiOrRFz8XTHZiVvD6+HqmJit4UCbN9LNpM5+/5hpyqgFRjoXx5POP/W06prdNEpKnEKF92/Tl1KefE7UgPesbhNpga3ayGXelBBuyTZDvhFMAMBLSgkK5xXsjmHdk72Ivfir1Jm+0aWCUEo4PFagVin0AGY2VpnE7xROltSi/J+eCUp9YD5nTwLLCSN/G97aAzy4HLUBt2KKrU4wPBNO+tYZD1i25QFncS0x9jdXY32gb7cUuieqtxFJZwhT6ERrYGmbjLWiDInwDWH3QUy7GovgrhdWrTF5P6HiSn/DruIjPFNjQ/GFBI0SOHctfQgzoJCMUTv8Ciqdfx5fuubi5WJ3s42Nj0qSX+UArK0ZpyYTlfuW8tn1uZ3+uFnzjZumGBYvYEL6gLY1coLCnPYSalHhyTdAz1Kc2lTanU1W/nElzxhU7g2Rpc6ZFFueabpcfWFOAoWpYLIALwc/uInNE6+T+5s99TFxfVN6Hwl06f6f1sM5+3dJhh4abjzuimTUDx5ZpOFHg0A==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
