---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snwbr.net
  namespace: services
spec:
  dnsNames:
    - snwbr.net
    # - ingress.snwbr.net
  secretName: snwbr-net-tls
  issuerRef:
    name: ingress
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: services

spec:
  defaultCertificate:
    secretName: snwbr-net-tls
