name: 'Node App CI'

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  deploy_code:
    name: 'Build and test'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: ./src/
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    ## Code quality and build

    - run: npm test
